### ISSUE TITLE
Crash when using /invsorter bladd

### ISSUE THREAD

**Issue by 04Slash** [cpw/inventorysorter#103]
**Forge Version:** 1.16.3-34.1.42
**Inventory Sorter Version:** 1.16.1-18.1.0
No other mods present

**Steps to reproduce:**
1. Install forge + mod.
2. Create a single player world (unsure if this issue exists in multiplayer)
3. Type /invsorter bladd then press space.
4. Proceed to crash.

[Crash report](https://pastebin.com/Sc2F6mHT)

I noticed the jar name is labeled 1.16.1. Is this version suppose to be compatible with 1.16.3? It's currently marked compatible with 1.16.3 on CurseForge.

**Comment by Alaric323** [comment]
Can confirm this as well, happens regardless of if an inventory has been sorted since loading the world or not.
