### ISSUE TITLE
Why this mod requires to be on the server?

### ISSUE THREAD

**Issue by st4s1k** [cpw/inventorysorter#106]
Hi, my question is written in the title. I encountered a "problem" (not really), that I couldn't find which mod causes problems entering the server telling me that mod list mismatch and I found out that it is this mod causing that. I remember InvTweaks being a client-side mod, so why does this mod require to be on the server? Thanks!

![image](https://user-images.githubusercontent.com/16061794/105425355-df190f80-5c51-11eb-8485-3b6b7a442c00.png)

**Comment by remplerus** [comment]
not exactly, inventory tweaks wasnt a client side only mod, you had to install it on the server too or you've been kicked.

**Comment by EnigmaTLOD** [comment]
You only ever got kicked if you spammed the sort command, it was purely a rate limiting problem, I used it on vanilla servers without issue keeping that in mind.

**Comment by cpw** [comment]
Because that's how it's designed. By sorting serverside, you avoid a lot of potential problems with stuff like NBT data and ratelimiting, especially for BIG containers.
