### ISSUE TITLE
Vanilla Client Connection to Server Forbidden in 19.0.0

### ISSUE THREAD

**Issue by Trajectory989** [cpw/inventorysorter#111]
Hello,

I notice that version 19.0.0 does not allow vanilla connections in MC 1.18. I have played with mods for so long that the loss of a middle click for sorting is truly unbearable so I added inventory sorter to my client and server. I wanted to see if my vanilla only friends could log in with 3 mods on the server (wthit 4.3.1, jei 9.0.0.40, and this version 19.0.0) and this seems to be the only mod to declare issue with vanilla players per the console (and I know it tested ok with a vanilla client when only wthit was on the server).

Would it be possible to still enable compatibility in the upcoming updates?

**Comment by danivalls** [comment]
Upvoting! Accepting connections from vanilla clients is a must nowadays

**Comment by cpw** [comment]
Not an issue. This is only intended to be used with modded servers.

**Comment by danivalls** [comment]
I agree about modded servers, but, what if a vanilla client tries to connect with the modded server? why should the connection be rejected? It would make more sense to allow the vanilla client to connect, it just wouldn't be able to use the mod because the client does not have it installed.
