### ISSUE TITLE
Support for Filtered Chests in 1.18.1

### ISSUE THREAD

**Issue by ClaudiusMinimus** [cpw/inventorysorter#113]
Can you add support for the mod,  [Filtered Chests](https://www.curseforge.com/minecraft/mc-mods/filtered-chests/files/3563810) Inventory Sorter works with most storage, but not with Filtered Chests. I am including your mod in my pack [Create on a Potato PC](https://www.curseforge.com/minecraft/modpacks/create-on-a-potato).

- Minecraft 1.18.1
- filteredchests-1.18.1-1.0.2.jar
- inventorysorter-1.18-19.0.0.jar

Thank you,

CM

**Comment by cpw** [comment]
Very unlikely.
