### ISSUE TITLE
there is not a 1.17.1 version out

### ISSUE THREAD

**Issue by KniveZout** [cpw/inventorysorter#115]
hi im a mine crafter and i love all types of mods and ive been using this inventory sorter mod for a years and i was looking in to the tough as nails mod and 1.17.1 to be exactly and i found out that this mod the best inventory sorter mods ik doesn't have a 1.17.1 version and im asking you (the creator) and who ever else reads this to help me and other have a 1.17.1 versions to play on 

thank you 
-KniveZout

**Comment by cpw** [comment]
And there won't be. I skipped it.
