### ISSUE TITLE
1.17.1 effort

### ISSUE THREAD

**Issue by astynax777** [cpw/inventorysorter#117]
Valhelsia 4 uses 1.17.1 and this is missing from it.  If I were to fork this and attempt to get 1.17.1 compatibility, what do you think the level of effort would be?

**Comment by cpw** [comment]
Low, but i'm not interested in doing it. 1.17 is done for modded MC IMO.

**Comment by astynax777** [comment]
> Low, but i'm not interested in doing it. 1.17 is done for modded MC IMO.

Thanks.  I wasn't suggesting that.  I'll work on it.

**Comment by astynax777** [comment]
You're right - it was pretty low effort. Appreciate all your work. 
[v1.17.1](https://github.com/astynax777/inventorysorter)
