### ISSUE TITLE
Compatibility with mod Sophisticated Backpacks

### ISSUE THREAD

**Issue by DoctorSigma** [cpw/inventorysorter#120]
I play with your mod and with the Sophisticated Backpacks mod. This mod adds backpacks in which you can insert upgrades. There is such an upgrade as "sophisticatedbackpacks: stack_upgrade_tier_1". It allows you to keep more than 64 items in one backpack in one slot. Specifically, this upgrade allows you to keep two stacks in one slot. When sorting with your mod, items that have more than two stacks in the slot are moved to two slots, and other items are moved. But when this happens and when the backpack is full, items that did not fit in disappear, do not fall out and disappear. In the very fashion for backpacks there is a sort, but sometimes out of habit in the backpack I forget about this bug and some of my things disappear.

Can you so that the sorting is not "absorbed into two or more slots", well, or do so so that your mod could not sort the inventory of backpacks?

Minecraft: 1.16.5
InventorySorter version: 18.1.0
Sophisticated Backpacks version: 3.15.1.503
Forge version: 36.2.21

**Comment by SuperKael** [comment]
I can confirm this issue for 1.18.1 as well, in the All the Mods 7 modpack.
