### ISSUE TITLE
Whitelist some heterogeneous containers.

### ISSUE THREAD

**Issue by Naturaspell** [cpw/inventorysorter#124]
Hi.
It sounds like Inventory Sorter ignores containers using different slot classes, am I right? 

Would it be possible to add an API or IMC to whitelist some containers (since I need it for my mod [Filtered Chests](https://www.curseforge.com/minecraft/mc-mods/filtered-chests))? Hopefully it wouldn't break Inventory Sorter.
As far as I know there's no issue between my mod and other sorting mods, so I think it should be fine with Inventory Sorter too.

Thank you.

inventorysorter-1.18-19.0.0

**Comment by cpw** [comment]
Yes, this is by design. Heterogeneous containers with different slot types break the simple sorting algorithm I use. I don't want to complicate it by trying to support multiple slot types in a single container.
