### ISSUE TITLE
Why is it necessary to install mod on the server?

### ISSUE THREAD

**Issue by joe-vettek** [cpw/inventorysorter#125]
I like your mod very much. It's convenient and compact. There's no ugly GUI, but unfortunately it can't be installed only on the client. Personally, I don't think this is cheating mod.
https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next
This kind of mod can only be installed on the client, but I don't like its interface and cumbersome functions.
I hope it can be improved. Otherwise I can't use it when I go to the server.

**Comment by cpw** [comment]
The sorting is done directly on the server, to avoid problems with itemstack replication and incomplete itemstack on the client. That's why it works so well. But to do that, it _needs to be on the server_.
