### ISSUE TITLE
1.18.2 Upgrade

### ISSUE THREAD

**Issue by RoyalReject** [cpw/inventorysorter#131]
I have tested the 1.18-19.0.0 on 1.18.2 and it seems to function normally, Could we get it marked comparable on curseforge to add into packs

**Comment by JRitmeester** [comment]
Does not work for me on 1.18.2 on Forge 40.0.44.

**Comment by BewitchingPetrichor** [comment]
How did you get it to work? I doesn't work for me using Forge 40.1.0
