### ISSUE TITLE
1.19 update does not produce a working jar

### ISSUE THREAD

**Issue by CCF100** [cpw/inventorysorter#136]
Fabric completely ingores the 1.19 jar, at least with my testing...

**Comment by meza** [comment]
Same here

**Comment by drakray** [comment]
it's a Forge mod, it will not work on Fabric

**Comment by Gofawu** [comment]
Don't work on Forge either. Don't know why, worked on 1.18 but not 1.19.

**Comment by Bakouru** [comment]
For MC 1.19.2 and 1.19.2-forge-43.1.1 I am using inventorysorter-1.19-20.0.0.jar in the server's mods folder and inventorysorter-1.19.2-21.0.0.jar within my %appdata%\.minecraft\mods folder. MC will complain that the versions don't match but the inventory sorter mod is fully working for me with this configuration.
