### ISSUE TITLE
Crash with latest Forge versions

### ISSUE THREAD

**Issue by MelanX** [cpw/inventorysorter#142]
This might be the result of the two breaking changes. 
This issue is a reminder for that only since I had the problem, too. I just forgot to update one of my mods for these changes.
If you still want versions, I'll provide them. And a log.

**Comment by Sanastae** [comment]
Had a crash too with the latest forge version (41.0.107) using the Inventory Sorter v20.0.0.
It happens when launching the game.
There is my crash report: [crash-2022-07-22_13.29.21-fml.txt](https://github.com/cpw/inventorysorter/files/9167342/crash-2022-07-22_13.29.21-fml.txt)

**Comment by rakzoser** [comment]
> Had a crash too with the latest forge version (41.0.107) using the Inventory Sorter v20.0.0. It happens when launching the game. There is my crash report: [crash-2022-07-22_13.29.21-fml.txt](https://github.com/cpw/inventorysorter/files/9167342/crash-2022-07-22_13.29.21-fml.txt)

literally have same issue, need a fix

**Comment by ProsperCraft** [comment]
Same with forge 110

**Comment by planetjohn16** [comment]
Same here with forge 110

**Comment by Spittys** [comment]
still not working on forge 110

**Comment by Bakouru** [comment]
For MC 1.19.2 and 1.19.2-forge-43.1.1 I am using inventorysorter-1.19-20.0.0.jar in the server's mods folder and inventorysorter-1.19.2-21.0.0.jar within my %appdata%\.minecraft\mods folder. MC will complain that the versions don't match but the inventory sorter mod is fully working for me with this configuration.
