### ISSUE TITLE
Error loading mods || Error has occured during loading || 1.19

### ISSUE THREAD

**Issue by spartan77898** [cpw/inventorysorter#144]
**Simple Invetory Sorter encountered an error during the side_setup event phase ||
java.lang.NoClassDefFoundError:net/minecraftforge/client/ScreenEvent$MouseClickedEvent$Pre**

I tried launching it without any other mods bur it still sends an error.

**Comment by Zwas** [comment]
I get a very similar message (1.19, forge, mac)-

Simple Inventory Sorter (inventorysorter) encountered an error during the sided_setup event phase
java.lang.NoClassDefFoundError:
net/minecraftforge/client/event/ScreenEvent$KeybordKeyPressedEvent$Pre

**Comment by rafael00kl** [comment]
same thing for me

**Comment by grothedev** [comment]
is this on a server? i got the same error on server start. 
here's my [log](https://hastebin.skyra.pw/raw/ihiliqifan)

**Comment by Bakouru** [comment]
For MC 1.19.2 and 1.19.2-forge-43.1.1 I am using inventorysorter-1.19-20.0.0.jar in the server's mods folder and inventorysorter-1.19.2-21.0.0.jar within my %appdata%\.minecraft\mods folder. MC will complain that the versions don't match but the inventory sorter mod is fully working for me with this configuration.
