### ISSUE TITLE
Crash During Setup Phase (1.19)

### ISSUE THREAD

**Issue by ArcTrooper210** [cpw/inventorysorter#148]
[crash-2022-09-05_12.07.32-fml.txt](https://github.com/cpw/inventorysorter/files/9491387/crash-2022-09-05_12.07.32-fml.txt)

There isn't a comments section so I'm just asking for help here

**Comment by Lothloriian** [comment]
I have the same issue when trying to add this mod to a 1.19 server as well.  I hope I attached the crash log right..
[crash-2022-09-24_22.27.35-fml.txt](https://github.com/cpw/inventorysorter/files/9639889/crash-2022-09-24_22.27.35-fml.txt)

**Comment by MichaelHillcox** [comment]
`1.19` is not supported but `1.19.2` is and that version is also considered the standard for modding on `1.19.x` versions
