### ISSUE TITLE
[1.9 - Crash]:

### ISSUE THREAD

**Issue by Lanse505** [cpw/inventorysorter#15]
Crash occurs when middle mouse clicking inside a chest to sort it's contents.

Forge Version:
forge 1.9-12.16.0.1865-1.9

Mod Version:
inventorysorter-1.9-0.7.10+29.jar

Crashlog:
http://puu.sh/olAR5/7e0e4745c3.txt

**Comment by Lanse505** [comment]
Full Log:
http://puu.sh/olB0c/abd1baf63e.log

**Comment by Jiraiyah** [comment]
same here, the error report : 

https://gist.github.com/Jiraiyah/ce3fc1d8b165c5334231f9ac2d5ea86a
