### ISSUE TITLE
Blacklist and showlast commands not working

### ISSUE THREAD

**Issue by penturt** [cpw/inventorysorter#158]
Blacklist and showlast commands not working

The command **/inventorysorter showlas**t always shows **inventorysorter:dummyplayerinventory** no matter what kind of chest is opened.

and command **/inventorysorter bladd** is not accepting any argument.

I even attempted to manually add blacklist to the config file, but the blacklist is not applied.

**Comment by MichaelHillcox** [comment]
Could you let me know what version of MC this was effecting?

**Comment by penturt** [comment]
Sorry this was a couple years back, I don't recall.

**Comment by MichaelHillcox** [comment]
No problem, that's for getting back to me regardless, hopefully this has been resolved with the latest versions I've pushed out :+1:
