### ISSUE TITLE
[1.19.3]  Crashing when game starts

### ISSUE THREAD

**Issue by anaooz** [cpw/inventorysorter#163]
[crash-2023-01-22_15.49.32-fml.txt](https://github.com/cpw/inventorysorter/files/10475239/crash-2023-01-22_15.49.32-fml.txt)
![image](https://user-images.githubusercontent.com/69781921/213934793-29f93c55-d962-4238-93b5-55a102de7d14.png)

**Comment by Dwitch87** [comment]
Same to me - there is not Update for 1.19.3 jet. Hopefully, it comes soon.
This Mod is greate and there is no alternative for Forge

**Comment by Dwitch87** [comment]
If I can help you in any way, please contact me. Also if you need German Translation, I could do that, too.
Thank you and best regards!
Dwitch

**Comment by agarcia967** [comment]
I'd also be happy to help in development!

**Comment by julesyan** [comment]
It seems this PR fixes this issue: https://github.com/cpw/inventorysorter/pull/161

**Comment by MichaelHillcox** [comment]
As `1.19.3` was a shortly lived patch version, we won't be adding support for it.

Please refer to #161 
> Closing - 19.3 & 4 was not a target for this mod, sorry.
