### ISSUE TITLE
[1.19.2 TLauncher] Not working 

### ISSUE THREAD

**Issue by noaimwastaken** [cpw/inventorysorter#164]
No matter if i scroll to get the items or if i click H button ( i had to change middle mouse toi H because i already had Middle mouse binded) nothing happens

**Comment by Dwitch87** [comment]
Did you test only using this mod? No other mods - and even default bindings, just for testing.
Just create a new instance, select forge and put the mod in the mods folder.
It worked fine for me... Maybe other mods do collidate

**Comment by Su5eD** [comment]
Pirated launchers are not supported. Buy the game.

**Comment by noaimwastaken** [comment]
Yeah that's fair tbh
