### ISSUE TITLE
[1.19.2] Not working/appearing in storage GUI

### ISSUE THREAD

**Issue by xenornithos** [cpw/inventorysorter#169]
Using version 1.19.2-21.0.4, with no other mods (to test). The mod's buttons fail to appear in the GUI of any of the storage blocks (chests, barrels), therefore this mod is unusable or basically nonexistent; no crashes, no errors, but simply does not seem to exist despite having it installed.

**Comment by MichaelHillcox** [comment]
This mod does not add buttons. You're thinking of inventory tweaks IIRC. You can use this mod by either scrolling or pressing the middle mouse button. Hope this helps :+1:
