### ISSUE TITLE
Doesn't work on server

### ISSUE THREAD

**Issue by lusokol** [cpw/inventorysorter#175]
It work in singleplayer but not in multiplayer, i am playing in a realms server in 1.20.1.
If you need extra info, tell me
Good luck !

**Comment by grouNDfx** [comment]
Sorting is done server side to avoid ghost items. If you want to be able to sort while you’re on a server, the server will need to be running the mod

**Comment by Unicod3r** [comment]
That's sad.

**Comment by Bucky420** [comment]
ikr
