### ISSUE TITLE
Item duplication - Progressive Automation 1.9

### ISSUE THREAD

**Issue by RaineAndrews** [cpw/inventorysorter#19]
Sorting the internal inventory of an iron miner from Progressive Automation (1.6.44) results in duplicated tools (specifically the visible items Iron Pickaxe, Iron Shovel, RF Engine. and cobblestone.

Obviously the mod is sorting these items from their respective slots into the internal inventory, but doesn't remove them from the respective slots.  The result is duping :(

**Comment by cpw** [comment]
Which version of inventory sorter? I have tried to stop virtual inventories from being accessible in the latest update.

**Comment by cpw** [comment]
OK, I see the issue. The PA inventory is monolithic, and some of the slots are weird. Some slots accept items, others do not. This means that the sorter sees all the items in all the slots, even those that are restricted as a single inventory for sorting purposes.

**Comment by cpw** [comment]
OK, the solution I'm using is that if the inventory is not monolithic - i.e. composed of identical slot types for all slots, then it will be ignored.
