### ISSUE TITLE
Modifying textures of sorting buttons for resource packs?

### ISSUE THREAD

**Issue by ebrdsht** [cpw/inventorysorter#190]
Hi! I'm not sure if I'm just inexperienced, but I was just trying to find where the textures for the buttons are located within the jar, I just wanted to be able to make them darker for a dark UI pack. Are they hard coded in in a different way?

**Comment by MichaelHillcox** [comment]
Not sure I follow? this mod does not contain any textures. I think you might be thinking of another mod. Let me know if I'm wrong here. Gunna close this for now
