### ISSUE TITLE
[inventorysorter-1.9.4-0.8.5+39] Sorting and scrolling not working

### ISSUE THREAD

**Issue by yovliporat** [cpw/inventorysorter#20]
I really don't know how to explain it, so I will try to provide as much info as I can. I downloaded the listed version (latest at the time of this issue being opened) and when I was trying to sort my inventory and scroll to move items, and it didn't work. The mod is not disabled, all the configs are on.
This is in a very small modpack I made for myself on curse, the mods are (with versions):
BloodMagic-1.9.4-2.0.1-40
Chameleon-1.9-2.1.4
chiselsandbits-10.2
inventorysorter-1.9.4-0.8.5+39
ironchest-1.9.4-6.0.141.782
jei_1.9.4-3.4.0.204
journeymap-1.9.4-5.2.0-unlimited
JustEnoughResources-1.9.4-0.4.5.31
Psi-beta-33
Quark-beta-21
StorageDrawers-1.9-3.1.7
StorageNetwork-1.9.4-1.11.1
Waila-1.7.0-B3_1.9.4
WailaHarvestability-mc1.9-1.1.7

Not that I think it matters, but Optifine, Fastcraft or any other mod of this type is not present. Just the mods listed.

-Yovli

**Comment by cpw** [comment]
Yup, that was a stupid bug by me!

**Comment by yovliporat** [comment]
Thank you very much CPW! Sorry for not responding with the answer, I've been busy. Good thing you didn't need my help :D
