### ISSUE TITLE
Minecraft. Modpack is not working. java.lang.IllegalStateException: Cannot get config value before config is loaded.

### ISSUE THREAD

**Issue by MrLobodobik** [cpw/inventorysorter#200]
I made the assembly. I divided it into 2 parts. One part of 133 mods. She works. The second part of the 31 mods. She's working too. When I connect minecraft, it does not start. The crash report says "java.lang.IllegalStateException: Cannot get config value before config is loaded."

Here is the crash report
[crash-2024-10-28_12.35.41-client.txt](https://github.com/user-attachments/files/17539091/crash-2024-10-28_12.35.41-client.txt)

**Comment by MichaelHillcox** [comment]
This issue has now been fixes in 1.21 versions of the mod :+1:
