### ISSUE TITLE
Armor Dup Bug

### ISSUE THREAD

**Issue by dannydjdk** [cpw/inventorysorter#22]
Version 0.10.0+42
Forge 12.18.2.2099

When middle clicking in an armor slot, the armor is duplicated in the main user inventory.

Problem noticed in this pack: https://minecraft.curseforge.com/projects/danny-sirenuse-pack
Inventory Tweaks was not enabled.

**Comment by Victorsueca** [comment]
Confirmed here
Discovered while playing Direwolf20 for 1.10.2

**Comment by OldDogy** [comment]
Re-Confirmed,
Sorry for the bump, consider dupes Extremely High Priority.

Cheers
