### ISSUE TITLE
Conflict with Applied Energistics

### ISSUE THREAD

**Issue by Xiaminou** [cpw/inventorysorter#24]
When browsing an Applied Energistics Terminal this mods prevents you from scrolling through the list while pointing at an item.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2627

#### Environment
- Minecraft Version: 1.10.2
- Forge Version: 2135

**Comment by cpw** [comment]
Hmmm, sounds like their scroll wheel handling conflicts with mine. I suspect they need to be a bit better about claiming the scroll wheel.
