### ISSUE TITLE
Items vanish on sort

### ISSUE THREAD

**Issue by charlesbevans** [cpw/inventorysorter#26]
I was sorting an Iron Chest and it went from nearly full to half full. I dug through the logs but couldn't find anything useful. Is there a debug mode or some way I could collect more information for you?

**Comment by cpw** [comment]
This bug is very vague. It's quite probable the items stacked up, so the visible number of stacks reduced. If you can reproduce, please reopen with a video showing what's going on.

**Comment by charlesbevans** [comment]
Sorry for not being more clear. Specific items definitely disappeared and were no longer available. I'm wondering if it's related to the EU2 bag of holding dupe bug. I'll reopen if I can force it to happen

**Comment by charlesbevans** [comment]
I haven't been able to intentionally replicate the problem, but it involves duping, so I thought you should know. Notice the two identical, down to the durability loss, TCon hammers. (Ignore the fact that I should have renamed it when I changed the head. ;) )There are also two EU2 wooden sickles with identical durability.
![screen shot 2016-12-29 at 11 31 35 am](https://cloud.githubusercontent.com/assets/15851438/21579322/b9526380-cf5d-11e6-9f85-dac82fc6f6ed.png)
