### ISSUE TITLE
Sort Control Binding config

### ISSUE THREAD

**Issue by DJ411** [cpw/inventorysorter#27]
Any possible way that the sorting button can be configurable? Have options to change the middle mouse key to something of our choosing?

**Comment by Jsimo42** [comment]
I was wondering the same thing I love this capability but my middle mouse button is broken and it would be useful to be able to change this binding.

**Comment by cpw** [comment]
No, not easily. The way keybindings behave in GUI screens makes extracting a keybinding extremely difficult, and introduces a lot of ways the mod could go wrong.
