### ISSUE TITLE
sporadic but recurring hotbar(?) item dupe/replace

### ISSUE THREAD

**Issue by shabble** [cpw/inventorysorter#30]
I've encountered some problem at least 6 or 7 times now (across several versions of SF3 pack) with personal inventory sorting (usually middle-clicking by accident, since I'm using a trackpad) destroying one of my items, and replacing it with a dupe of another item in my inventory.

It doesn't happen often enough (and sometimes I don't notice immediately) to pin down any proximate cause, so any suggestions on ways to debug would be appreciated.

It seems to primarily affect items on my hotbar, and in many (all?) cases I've noticed, it's been duping the item in slot 2 (my RS wireless grid). It always appears to destroy some other item when doing so, which I think is also usually from hotbar (where my nice tools live :()

It has never happened if I disable 'enable middle-click sorting' in the mod-options -> simple inventory sorter config, but I would liek to use it (especially on large chests and other non-player inventories) if I can.

A last note is that it *might* occur primarily when accessing a modded machine UI that includes the standard player inventory display, and I (mis)-middleclick there. I can't confirm that, and random testing under various conditions hasn't led to reproduction.

Versions:

* minecraft: 1.10.2
* forge: 12.18.3.2215
* inventorysorter: 0.10.5+46
* pack: SkyFactory 3.0.6b

**Comment by charlesbevans** [comment]
I've had it happen without the grid (although RF was installed) on several different mod packs. Today I was on a modified Sky Factory 3 and my sword and an unknown item were replaced with duped Tiny Progressions watering cans (none of them were in my hotbar).

**Comment by cpw** [comment]
Closing. If this happens with 1.12, I'll revisit. It might be a thread problem, or a filtering issue.
