### ISSUE TITLE
More hotkeys!

### ISSUE THREAD

**Issue by ShaunDreclin** [cpw/inventorysorter#31]
I'm really missing InventoryTweaks in packs that only have this mod. the list of hotkeys that I use are

Middle Click: Sort
Ctrl-Click/Mousewheel: Move one item
Shift-Click: Move a stack
Alt-Click: Drop a stack
Ctrl-Shift-Click: Move all stacks of item
Alt-Ctrl-Shift-Click: Drop all stacks of item
Space-Click: Move all items
Alt-Space-Click: Drop all items
W-Click: Move item from inventory to container/crafting interface
D-Click: Move item from container/crafting interface to inventory

Would be great if you could add what's missing of these!

**Comment by cpw** [comment]
Additional functions are a definite todo.

**Comment by Kenjinn13** [comment]
why was this mod taken over InventoryTweaks, I've done everything i can to get it to work, Middle-button sorting does not work, I've tried binding 10 different keys. I think InventoryTweaks was a much better mod as it just worked and had way more features.
