### ISSUE TITLE
Attempting to concurrently modify PlayerChunkMapEntry for chunk [290, -36]

### ISSUE THREAD

**Issue by Eufranio** [cpw/inventorysorter#32]
This stacktrace is randomly appearing in my console, and I've been told that it may be bad and you shouldn't modify the world directly from packet handlers.

Stacktrace: https://hastebin.com/asolokerem.md

**Comment by Eufranio** [comment]
Read https://github.com/cpw/inventorysorter/issues/33 :P

**Comment by cpw** [comment]
Fixed in 1.12. Server side processing happens in the server thread now.
