### ISSUE TITLE
Inventories are modified from a packet handler thread

### ISSUE THREAD

**Issue by Aaron1011** [cpw/inventorysorter#33]
[Action#execute](https://github.com/cpw/inventorysorter/blob/master/src/main/java/cpw/mods/inventorysorter/ServerHandler.java#L37) is directly called from a packet handler, which is not run on the main thread. This can adversely affect the game and other mods, which expect all interactions to take place on the main thread

**Comment by cpw** [comment]
Fixed in 1.12.
