### ISSUE TITLE
Some inventories are not supported?

### ISSUE THREAD

**Issue by DrakusorU** [cpw/inventorysorter#39]
I see some inventories are not supported, which side is responsible for implemeting the sorting feature? InventoryTweaks works but I don't like the fact that the buttons overlaps JEI..

The inventories I am talking about are ironbackpacks ( though ironchests works ) , storage crates from actually additions and I think they are more but just those I found until this moment not working..

**Comment by cpw** [comment]
I'll look at these inventories. Many don't work because I'm very conservative about which inventories I'll allow sorting in, to prevent dupe bugs.
