### ISSUE TITLE
NPE when sorting player inventory

### ISSUE THREAD

**Issue by shadowfacts** [cpw/inventorysorter#4]
Stacktrace: https://gist.github.com/shadowfacts/f781f15167bcb17e409b

After the exception, the client freezes and according to the log, the integrated server sees that the player has lost connection, the world saves, however the game does not actually crash. The game freezes and must manually be killed.

**Comment by whitestarx0312** [comment]
Yep I'm getting this too.

**Comment by cpw** [comment]
What did you do to trigger this?

**Comment by shadowfacts** [comment]
I middle-clicked in my player's inventory.

**Comment by cpw** [comment]
Yes, but that shouldn't happen. Does it reproduce? Or was it one off? Try with latest 1.8.9 or 1.9 build please.

**Comment by shadowfacts** [comment]
I tried to reproduce this a number of times with the 1.9 version and I couldn't reproduce it. This definitely happened multiple times before. It appears to have been fixed somewhere in the 1.9 update.

**Comment by cpw** [comment]
Thanks for checking!
