### ISSUE TITLE
Duplication bug when sorting a golden bag of holding (Extra Utilities)

### ISSUE THREAD

**Issue by belathus** [cpw/inventorysorter#40]
Inventory Sorter 1.12.2-1.12.4-52
Extra Utilities 2 1.6.8

 I'm not sure if this is Inventory Sorter or Extra Utilities, but... I keep accidentally sorting my golden bag, and every time I do, it doubles the contents of the bag.

**Comment by cpw** [comment]
That item (bag of holding) was disabled last time I checked. Perhaps this is partly why?

**Comment by SnowShock35** [comment]
@cpw It was disabled in Direwolf20 pack (possibly other FTB packs too). Sorry for the confusion.

**Comment by cpw** [comment]
No worries. A good test case for figuring out why we get dupes *sometimes*.

**Comment by cpw** [comment]
Fixed in latest release.
