### ISSUE TITLE
[Bug] Sorting voided items

### ISSUE THREAD

**Issue by RedSnt** [cpw/inventorysorter#41]
Playing Sky Factory 3, so MC v. 1.10.2 and v. 0.11.0+47 of inventorysorter. 

Bug happened when I had converted some loot bags from a higher tier to lower tier which results in stacks of lootbags of 4 - but once you remove them from that stack, they can't get restacked, so what happened was that maybe 10 stacks of 4 lootbags when auto-sorted just filled the inventory and erased some tools of mine and of course some of the remaining loot bags.

You can see it in [this gif](https://gyazo.com/36493204e17ba0bec37badbfe49680ea).

[![https://gyazo.com/36493204e17ba0bec37badbfe49680ea](https://i.gyazo.com/36493204e17ba0bec37badbfe49680ea.gif)](https://gyazo.com/36493204e17ba0bec37badbfe49680ea)

**Comment by cpw** [comment]
Sadly, the item forces a stack size of 1 and then violates its own rules by giving you 4. There's not much I can do except special case this, and every item that does this would need its own special casing. Just be aware this happens sometimes and have a chest handy.
