### ISSUE TITLE
Items Deleted from Industrial Foregoing Inventories

### ISSUE THREAD

**Issue by SciFiz** [cpw/inventorysorter#42]
Attempting to sort the animal feeder inventory (because it had been accepting non-feed items) deleted the items in it. Plant Sower & Potion Brewer can be sorted without issue. Spores Reactor, Enchantment Sorter, Petrified Fuel Generator deleted items. I checked for invisible/desync, and replicated in a test world.
IS 1.12.2-1.12.4+ 52
IF 1.12.2-1.6.3-107
Pack: DW20 1.12 1.4.0

IF also has a recently opened issue for this: https://github.com/Buuz135/Industrial-Foregoing/issues/129

**Comment by SnowShock35** [comment]
This is now technically fixed. You have to update Inventory Sorter and add the class name of the machines affected to the inventory sorter config. :-)

**Comment by cpw** [comment]
Yeah, this is technically a bug in industrial foregoing, it's container is behaving inconsistently. For the dw20 pack it's been blacklisted and won't sort anymore.
