### ISSUE TITLE
Mouse Wheel fast scrolling issue

### ISSUE THREAD

**Issue by Yarkin10418** [cpw/inventorysorter#44]
When i scroll my mouse wheel too fast i just pick the item. Using version 1.12.4 +52 of the mod

**Comment by SnowShock35** [comment]
@GizliKodcu Do you have any other mods installed? e.g. Mouse Tweaks, Inventory Tweaks, Item Scroller, Not Enough Items 1.8+?

**Comment by cpw** [comment]
I would echo what snow asks here. Mousewheel activity in my mod is 100% server side, it should never cause items to become stuck on the cursor. Note that default configuration of direwolf20 pack is to use mousetweaks wheel activity, mine is disabled..

**Comment by SnowShock35** [comment]
If you were playing the direwolf20 mod pack v1.5.0 you would've experienced this. It was later addressed in 1.6.0.
