### ISSUE TITLE
[1.12] Inventory Sorter causes dupe bugs with various mods due to sorting

### ISSUE THREAD

**Issue by SnowShock35** [cpw/inventorysorter#45]
Hi @cpw,

While I'm aware this issue has been reported a couple times I thought I'd try to be a bit more in-depth and through with it.

#### Issue Details

- Minecraft 1.12.2
- Minecraft Forge 14.23.1.2583
- Inventory Sorter 4+52
- Mods Tested w/:
  - Industrial Foregoing 1.6.6 (Items disappear w/ IF)
  - Industrial Craft 2.8.16
  - Extra Utilities 1.7.2

#### Issue Description

When using various inventories from these mods, with items in, using the middle mouse button will cause the items to duplicate in most cases and sometimes disappear. These are just some of the issues I've had reported I am sure there's many more.

I've tested the three I've mentioned in this post. However, I've heard reports of it happening in the inventory too.

* https://bt.industrial-craft.net/view.php?id=2295
* https://forum.feed-the-beast.com/threads/dupe-bug.263693/
* https://forum.feed-the-beast.com/threads/infinite-ic2-diamond-drills.263753/ (Same as first - The first one was a report I had made to IC2 tracker thinking it was ic2 causing it - that was before I had seen other reports)
* https://ss.blamesnow.co.uk/2018/01/1515113932-3e3f90eb.png (Back when the pack was in testing, testers said it would randomly delete content - which was why it was disabled in Dw20 pack - but now I believe it to be caused by this bug) 

#### Issue Media

Here's a GIF that someone made of the IC2 one https://imgur.com/a/HJSse

Here's a YouTube video that someone else made of Industrial Foregoing experiencing the same issue https://youtu.be/-rcdVK6jw6I

**Comment by cpw** [comment]
OK, I see it. These are just bad containers for various reasons. We can just blacklist sorting with that container open to stop it.

**Comment by SnowShock35** [comment]
Awesome. I'll get that in as soon as possible. Thanks for addressing this for me. :-)

**Comment by SnowShock35** [comment]
Closed via 4ebc8ced5a7f0315b770042cd673b86a7590df04
