### ISSUE TITLE
Feature Request: Debug Mode

### ISSUE THREAD

**Issue by SnowShock35** [cpw/inventorysorter#46]
Hi @cpw,

Would a debug config option be something you'd consider adding?

It would basically print the inventory a player just sorted to the console (the class name that is) So that you could know which ones to blacklist. This would be more helpful for mods who's code is closed source where you don't really know the class name.

**Comment by cpw** [comment]
It should already be doing this.. the container name should be logged at debug level..

**Comment by SnowShock35** [comment]
So, another mod author also said to me that should be the case as I asked them what the name of the container was that needed blacklisting but it just had a number like 25 or 26 in the log no class names. Was this fixed in the newer version you've just released?
