### ISSUE TITLE
[Minecraft 1.12.2 - mod v1.13.1+55 - Forge 14.23.1.2601] Middle click to sort doesn't work in creative

### ISSUE THREAD

**Issue by VallenFrostweaver** [cpw/inventorysorter#48]
Pretty simple. When in gamemode 1 middle click doesn't work but when in gamemode 0 it does.

**Comment by cpw** [comment]
this is by design, since middle click is usually doing something else in creative.

**Comment by VaporeonScripts** [comment]
> this is by design, since middle click is usually doing something else in creative.

people often rebind it to something else, so adding it in the config would be good
