### ISSUE TITLE
Item Deletion

### ISSUE THREAD

**Issue by CakeFlour** [cpw/inventorysorter#49]
I haven't been able to gather much info on the matter. but it seems like this is a result of the Item Duplication bug a few version ago. 
In this scenario though sorting the hotbar while a portable inventory is in it will outright cause it to vanish along with any items in it. This occurs in both Single and Multiplayer.
Re logging on Multiplayer servers does not fix it.

**Comment by enigma0Z** [comment]
Confirmed I have the same behavior on my client/server as well

**Comment by jbell-shibumi** [comment]
Can we use bladd to blacklist the hotbar till it's properly fixed? That'd be an easy way to fix it for now...

**Comment by cpw** [comment]
I saw this bug with an older version, but have failed to reproduce the issue with a variety of setups. It's possible the portable inventory had a bug where it was somehow allowing it's slot to be overwritten, since fixed?
