### ISSUE TITLE
Middle click in Compacter = items lost

### ISSUE THREAD

**Issue by neoc666** [cpw/inventorysorter#58]
StoneBlock 1.0.20
compacter-1.3.0.3-mc1.12.2
inventorysorter-1.12.2-1.13.3+57

I used middle click in the output inventory of the Compacter, all items in the machine disappeared. Could as well be a Compacter issue if it doesn't implement inventory access correctly.

**Comment by cpw** [comment]
It does not. Add it to the sort blacklist using the /inventorysorter blacklist command so you don't accidentally trigger it. Sadly, handling every possible fault in other mods is impossible.

**Comment by neoc666** [comment]
Thanks!
