### ISSUE TITLE
Sorting GTCE Chests Causes Everything From Your Inventory To Go Into Them

### ISSUE THREAD

**Issue by TheLimePixel** [cpw/inventorysorter#60]
When middle-clicking for sorting in GregTech Community Edition's Chests, everything from the player's inventory goes into them.

**Comment by cpw** [comment]
Sounds like he's got broken slot and inventory grouping in his container.

**Comment by TookUrSweetRoll** [comment]
Same happens with Metal Barrels mod. Similar issue?

**Comment by Tfarcenim** [comment]
I'm looking for how to fix this on my end

**Comment by ct-klein** [comment]
any update on this issue?
