### ISSUE TITLE
1.14.2 Crash

### ISSUE THREAD

**Issue by RedBullSlurpie** [cpw/inventorysorter#62]
I used the middle mouse click to sort INV and the game crashed. Here is the crash report.
https://pastebin.com/iCB5C8Qw

MC Version: 1.14.2
Forge Version: 26.0.63
INV Sorter Version: 14.3.5

**Comment by cpw** [comment]
Thanks. I'll be doing a full refresh of this mod soon.

**Comment by cpw** [comment]
Closing, should be fixed with 15.x versions.
