### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by vizthex123** [cpw/inventorysorter#65]
I noticed that this mod just doesn't work.

I'm using it on a server, and it should still work right?

**Comment by pyrosshade** [comment]
> The mod requires installation on both client and server to function.
This is mentioned on the readme of the project.

**Comment by ProsperCraft** [comment]
Works for me, having it on the server and client, press middle mouse button.

**Comment by cpw** [comment]
Closing. The recent versions work.
