### ISSUE TITLE
Item dupe with Thaumcraft 5

### ISSUE THREAD

**Issue by jrdroney** [cpw/inventorysorter#7]
Bug with Thaumcraft-1.8.9-5.1.4 and inventorysorter-1.8.9-0.7.2+24. Sorting an Arcane Workbench duplicates the wand currently in the workbench.

**Comment by PROdotes** [comment]
Since baubles is part of TC I'll just add that sorting when you have the baubles window open duplicates all your armor and baubles

**Comment by milla-sedai** [comment]
> Since baubles is part of TC I'll just add that sorting when you have the baubles window open duplicates all your armor and baubles

Still happens with forge 1902, and the following mods, bolded TC/Baubles, and Inventory Sorter versions (latest)

**Baubles-1.8.9-1.1.3.0.jar"**

Botania-unofficial.r1.8-299.jar"
Chameleon-1.8.9-1.1.2.jar"
CompassCoords-1.8.9-0.2.6.jar"
FastLeafDecay-1.8-1.6.jar"
hopperducts-mc1.8.8-1.4.6.jar"
ironchest-1.8.9-6.0.125.770.jar"
**inventorysorter-1.8.9-0.7.7+27.jar"**
jei_1.8.9-2.28.18.186.jar"
JEIAddons_1.8.9-0.12.0.57.jar"
journeymap-1.8.9-5.2.0-unlimited.jar"
JustEnoughResources-1.8.9-0.4.0.23.jar"
LLOverlayReloaded-1.0.7-mc1.8.9.jar"
StorageDrawers-1.8.9-2.6.4.jar"
**Thaumcraft-1.8.9-5.2.4.jar"**
Waila-1.6.0-B3_1.8.8.jar"

Out of curiosity is 1.8.9 considered deprecated or obsolete in the modding circle? Should I just move on?
