### ISSUE TITLE
Error while launching MC

### ISSUE THREAD

**Issue by konkun1998** [cpw/inventorysorter#80]
New update is not working.
![image](https://user-images.githubusercontent.com/30831363/65130652-2cea8b80-d9fe-11e9-9eac-9f07f0254850.png)

**Comment by apollo-mg** [comment]
On mine as well.

**Comment by JFGTX** [comment]
The same for me :/ But when it worked, it only work in solo, not multi ...

**Comment by cpw** [comment]
Not compatible with forge RB
