### ISSUE TITLE
No config file generated 1.14.4-16.2.0 (Twitch App installer)

### ISSUE THREAD

**Issue by RepoDraghon** [cpw/inventorysorter#83]
I've tried to copy and paste from an earlier minecraft version but it didn't work. Scroll wheel to set keybind does not work for me, it simply does nothing till I actually press a keyboard button... A config file could fix that...
some pics confirm it's installed but others make it look like it wasn't yet it does indeed work in-game...

![Screenshot (1)](https://user-images.githubusercontent.com/8423696/67073638-62d57980-f13c-11e9-9916-2428060f582e.png)
![Screenshot (2)](https://user-images.githubusercontent.com/8423696/67073639-636e1000-f13c-11e9-8143-2d4e1a6c4c8b.png)
![Screenshot (3)](https://user-images.githubusercontent.com/8423696/67073640-636e1000-f13c-11e9-9ff1-7e9415d89d77.png)
![Screenshot (4)](https://user-images.githubusercontent.com/8423696/67073641-636e1000-f13c-11e9-8fbc-8bc8a52516c5.png)
![Screenshot (5)](https://user-images.githubusercontent.com/8423696/67073642-636e1000-f13c-11e9-8b52-46b3f0ed1096.png)

**Comment by cpw** [comment]
Configuration is stored inside the server. Please learn about the new configuration model in 1.14.
