### ISSUE TITLE
error in common_setup phase

### ISSUE THREAD

**Issue by CharaViolet** [cpw/inventorysorter#84]
I'm trying to open forge with this mod but I keep getting this error:
![image](https://user-images.githubusercontent.com/28274295/67112835-83d6b280-f1ae-11e9-94bb-4971cc8e1723.png)

**Comment by MythikAngel** [comment]
Also happening for me with version 16.2.0

**Comment by tashaxe** [comment]
I'm experiencing the same issue and am also running 16.2.0 with Forge 28.1.0

**Comment by cpw** [comment]
This is not a useful bug report. Please include the debug log file...

**Comment by IZ41** [comment]
> This is not a useful bug report. Please include the debug log file...

[error.txt](https://github.com/cpw/inventorysorter/files/3764289/error.txt)

**Comment by IZ41** [comment]
> This is not a useful bug report. Please include the debug log file...

Have the same problem. 1.14.4 Forge-28.1.0
[error.txt](https://github.com/cpw/inventorysorter/files/3764320/error.txt)

**Comment by IAmCaligvla** [comment]
I'm also having this issue. Here's the log:
[latest.log](https://github.com/cpw/inventorysorter/files/3801045/latest.log)

**Comment by cpw** [comment]
I am not compatible with the RB of forge right now.
