### ISSUE TITLE
npt working with last forge version

### ISSUE THREAD

**Issue by MAKUKO7777** [cpw/inventorysorter#85]
Please help. The mod is not loading with last forge version

**Comment by Morteux** [comment]
Same here. Error when loading common_setup

**Comment by Cyankun** [comment]
Same. It says ''Simple inventory Sorter (inventorysorter) encountered an error during the common_setup event phase.''
I'm using Forge 1.14.4 - 28.1.0

**Comment by greasenose** [comment]
simple workaround: use the lastest version of forge, not the recommended one.
