### ISSUE TITLE
1.14 item deletion when slots dont accept items

### ISSUE THREAD

**Issue by mcenderdragon** [cpw/inventorysorter#89]
In 1.14 I sorted a "corpse" inventory by accident and lost all of my items. It seems like if the Slot returns for isItemValid false the item just gets deleted. I think there are better ways to handle this (like abort the sorting and if the item can not be added to the players inventory drop it)

Issue there: https://www.curseforge.com/minecraft/mc-mods/corpse/issues/20

**Comment by Aeledfyr** [comment]
This appears to also be an issue with 1.16.4.  Attempting to sort in any machine from Industrial Foregoing will delete its inventory rather than aborting the sort or dropping the items.

**Comment by UnhappyCodings** [comment]
At me the same error occur with every Industrial Foregoing machine. But after the sorting I cant even put any upgrade in any slot of any machine anymore.
