### ISSUE TITLE
Duplication of Axe in Neotechs Electric Logger when inventory sort triggered

### ISSUE THREAD

**Issue by flipwalker42** [cpw/inventorysorter#9]
Version:0.7.4+26

When using Neotech's Electric logger in current FTB Unstable if you sort while in it's inventory it duplicates the axe in the 'axe' slot, placing the duplicate in the main inventory of the machine. Also posted on Neotech's bug list.

As a side note it looks like it might be the same issue as the other duplication bugs, but just in case it's not I decided to make a new issue anyway. Sorry if it is the same.

**Comment by cpw** [comment]
Sorting should not trigger dupes. Scroll wheeling did. I would suspect that the slot is not marked properly to protect it's content from sorting. It should accept putStack(null) and remove the item. Ideally, it should be a separate container in the inventory, that way it won't even be considered for sorting.
