### ISSUE TITLE
Blacklist AE/ME Terminals

### ISSUE THREAD

**Issue by budgej** [cpw/inventorysorter#97]
Minecraft 1.15.2, Forge 31.2.31, Inventory Sorter 17.0.0

![image](https://user-images.githubusercontent.com/3517766/89806754-8d4a5600-db05-11ea-8cd0-61426f4e4461.png)

/invsorter list reports [appliedenergistics2:crafting_terminal], but the buttons still appear.  /invsorter showlast reports [inventorysorter:dummyplayercontainer] no matter what inventory I sorted with middle mouse click last (including Minecraft chests).

**Comment by cpw** [comment]
Not my mod.
