### ISSUE TITLE
Error on load: Missing Licence information 18.0.0

### ISSUE THREAD

**Issue by Bjamse** [cpw/inventorysorter#99]
**Error message:** 
```
Missing Licence information in file Mod File:
<path>\inventorysorter-1.16.1-18.0.0.jar
```

**Setup:**
- Minecraft 1.16.3
- Forge 34.1.0
- mods:
   - inventorysorter-1.16.1-18.0.0.jar

Full crash report [ here](https://pastebin.com/Uf6SZgPz)

**Comment by Ja2012** [comment]
same
rep https://zerobin.net/?8b373e3bc888b8e7#9X9fuY27LymWzR+N1MP/36FDDrcwW3lnkj4umrinHPs=
